<a href="https://colab.research.google.com/github/dushyantsharma460/Competitive-Programming-Project-Sem1/blob/main/CollegeProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('Olympics.csv')

In [ ]:
df.head(3)

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal
0,1,A Dijiang,M,24,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      100 non-null    int64
 1   name    100 non-null    object
 2   sex     100 non-null    object
 3   age     100 non-null    int64
 4   height  84 non-null     float64
 5   weight  81 non-null     float64
 6   team    100 non-null    object
 7   noc     100 non-null    object
 8   games   100 non-null    object
 9   year    100 non-null    int64
 10  season  100 non-null    object
 11  city    100 non-null    object
 12  sport   100 non-null    object
 13  event   100 non-null    object
 14  medal   21 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 11.8+ KB

In [ ]:
df.isnull().sum()

id         0
name       0
sex        0
age        0
height    16
weight    19
team       0
noc        0
games      0
year       0
season     0
city       0
sport      0
event      0
medal     79
dtype: int64

In [ ]:
df['medal'].fillna(value=0, inplace=True)

In [ ]:
df['height'].fillna(method='bfill', inplace=True)

In [ ]:
df['weight'].fillna(method='bfill', inplace=True)

In [ ]:
df.isnull().sum()

id        0
name      0
sex       0
age       0
height    0
weight    0
team      0
noc       0
games     0
year      0
season    0
city      0
sport     0
event     0
medal     0
dtype: int64

In [ ]:
athlete_medals = df[['name', 'medal']]
athlete_medals

                                  name medal
0                            A Dijiang     0
1                             A Lamusi     0
2                  Gunnar Nielsen Aaby     0
3                 Edgar Lindenau Aabye  Gold
4             Christine Jacoba Aaftink     0
..                                 ...   ...
95                Olav Augunson Aarnes     0
96                 Mika Lauri Aarnikka     0
97                 Mika Lauri Aarnikka     0
98  Jamale (Djamel-) Aarrass (Ahrass-)     0
99              Dagfinn Sverre Aarskog     0

[100 rows x 2 columns]

In [ ]:
athlete_counts = df['name'].value_counts()
non_duplicated_athletes = athlete_counts[athlete_counts == 1].index.tolist()
num_non_duplicated_athletes = len(non_duplicated_athletes)
print("The number of non duplalicsted athletes: ",num_non_duplicated_athletes)

The number of non duplalicsted athletes:  22

In [ ]:
gold_medal_athletes = df[df['medal'] == 'Gold']
number_of_athletets_win_gold_medals=len(gold_medal_athletes)
print("The number of athletets_win_gold_medals: ",number_of_athletets_win_gold_medals)

The number of athletets_win_gold_medals:  9

In [ ]:
silver_medal_athletes = df[df['medal'] == 'Silver']
silver_ordered_by_year = silver_medal_athletes.sort_values(by='year')
silver_ordered_by_year

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal
86,25,Alf Lied Aanning,M,24,169.0,65.0,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Gymnastics,"""Gymnastics Men's Team All-Around, Free System""",Silver
63,20,Kjetil Andr Aamodt,M,22,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Downhill,Silver
67,20,Kjetil Andr Aamodt,M,22,176.0,85.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Alpine Skiing,Alpine Skiing Men's Combined,Silver
92,30,Pepijn Aardewijn,M,26,189.0,72.0,Netherlands,NED,1996 Summer,1996,Summer,Atlanta,Rowing,Rowing Men's Lightweight Double Sculls,Silver

In [ ]:
medal_counts = df.groupby('team')['medal'].value_counts().unstack().fillna(0)
medal_counts

medal              0  Bronze  Gold  Silver
team
China            2.0     0.0   0.0     0.0
Denmark          1.0     0.0   0.0     0.0
Denmark/Sweden   0.0     0.0   1.0     0.0
Estonia          1.0     0.0   0.0     0.0
Finland         25.0     5.0   3.0     0.0
France           1.0     0.0   0.0     0.0
Netherlands     10.0     1.0   0.0     1.0
Norway          22.0     2.0   5.0     3.0
Romania          1.0     0.0   0.0     0.0
United States   16.0     0.0   0.0     0.0

In [ ]:
most_medals_athlete = df['name'].value_counts().idxmax()
print("The most medakl wiun by the athlete: ",most_medals_athlete)

The most medakl wiun by the athlete:  Kjetil Andr Aamodt

In [ ]:
freestyle_events = df[df['event'].str.contains('Freestyle', case=False)]['event'].unique()
print("The Freestyle Event is : ",freestyle_events)

The Freestyle Event is :  ["Swimming Men's 400 metres Freestyle"]

In [ ]:
top_3_athletes_by_sport = df.groupby(['sport', 'name'])['medal'].count().reset_index(name='medal_count')
top_3_athletes_by_sport = top_3_athletes_by_sport.sort_values(['sport', 'medal_count'], ascending=[True, False]).groupby('sport').head(3)
top_3_athletes_by_sport

                   sport                                  name  medal_count
0          Alpine Skiing                    Kjetil Andr Aamodt           20
1       Art Competitions                 Win Valdemar Aaltonen            1
2              Athletics  Cornelia \Cor\" Aalten (-Strannood)"            2
3              Athletics                     Evald rma (rman-)            1
4              Athletics    Jamale (Djamel-) Aarrass (Ahrass-)            1
7              Badminton                     Jyri Tapani Aalto            1
8             Basketball                             A Dijiang            1
9               Biathlon        Pirjo Hannele Aalto (Mattila-)            1
10             Bobsleigh                Dagfinn Sverre Aarskog            1
11  Cross Country Skiing                          John Aalberg            8
13  Cross Country Skiing                       Per Knut Aaland            8
12  Cross Country Skiing                    Jorma Ilmari Aalto            1
14              Football                   Gunnar Nielsen Aaby            1
16            Gymnastics               Paavo Johannes Aaltonen           16
15            Gymnastics                      Alf Lied Aanning            1
17              Handball             Ragnhild Margrethe Aamodt            1
18                Hockey                  Willemien Aardenburg            1
19            Ice Hockey                      Antti Sami Aalto            1
20            Ice Hockey              Juhamatti Tapio Aaltonen            1
21                  Judo                              A Lamusi            1
22                  Luge          Agnes Erika Aanonsen (-Eyde)            1
23                Rowing                      Pepijn Aardewijn            2
24               Sailing                      Jan-Erik Aarberg            2
25               Sailing                   Mika Lauri Aarnikka            2
26               Sailing                    Minna Maarit Aalto            2
27         Speed Skating              Christine Jacoba Aaftink            6
28         Speed Skating                      Nils Egil Aaness            3
29              Swimming                  Arvo Ossian Aaltonen            5
30              Swimming      Einar Ferdinand \Einari\" Aalto"            1
31            Tug-Of-War                  Edgar Lindenau Aabye            1
32            Water Polo                         Johan Aantjes            1
33         Weightlifting                         Andreea Aanei            1
34             Wrestling                           Fritz Aanes            2

In [ ]:
athletes_multiple_medals = df.groupby(['year', 'name'])['medal'].count()
athletes_multiple_medals = athletes_multiple_medals[athletes_multiple_medals > 1].reset_index(name='medal_count')
athletes_multiple_medals

    year                                  name  medal_count
0   1912                  Arvo Ossian Aaltonen            2
1   1920                  Arvo Ossian Aaltonen            2
2   1932  Cornelia \Cor\" Aalten (-Strannood)"            2
3   1948               Paavo Johannes Aaltonen            8
4   1952               Paavo Johannes Aaltonen            8
5   1960                      Nils Egil Aaness            2
6   1988              Christine Jacoba Aaftink            2
7   1992              Christine Jacoba Aaftink            2
8   1992                          John Aalberg            4
9   1992                    Kjetil Andr Aamodt            4
10  1992                       Per Knut Aaland            4
11  1994              Christine Jacoba Aaftink            2
12  1994                          John Aalberg            4
13  1994                    Kjetil Andr Aamodt            5
14  1994                       Per Knut Aaland            4
15  1998                    Kjetil Andr Aamodt            4
16  2002                    Kjetil Andr Aamodt            5
17  2006                    Kjetil Andr Aamodt            2

In [ ]:
df.head()

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal
0,1,A Dijiang,M,24,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,0
1,2,A Lamusi,M,23,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,0
2,3,Gunnar Nielsen Aaby,M,24,185.0,82.0,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,0
3,4,Edgar Lindenau Aabye,M,34,185.0,82.0,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,0

In [ ]:
summer_gold = df.loc[(df['season'] == 'Summer') & (df['medal'] == 'Gold'), 'team'].unique()
winter_gold = df.loc[(df['season'] == 'Winter') & (df['medal'] == 'Gold'), 'team'].unique()
countries_winning_both = set(summer_gold) & set(winter_gold)
countries_winning_both

{'Norway'}

In [ ]:
first_medal_year = df.groupby('team')['year'].min()
last_medal_year = df.groupby('team')['year'].max()
year_difference = last_medal_year - first_medal_year
year_difference

team
China              20
Denmark             0
Denmark/Sweden      0
Estonia             0
Finland           102
France              0
Netherlands        68
Norway             96
Romania             0
United States       2
Name: year, dtype: int64

In [ ]:
silver_athletes = df[df['medal'] == 'Silver'][['name', 'event', 'year']]
gold_athletes = df[df['medal'] == 'Gold'][['name', 'event', 'year']]

silver_gold_athletes = silver_athletes.merge(gold_athletes, on=['name', 'event'], suffixes=('_silver', '_gold'))
silver_gold_athletes

                 name                         event  year_silver  year_gold
0  Kjetil Andr Aamodt  Alpine Skiing Men's Combined         1994       2002

In [ ]:
countries_medals = df.groupby('noc')['sport'].nunique()
countries_with_more_than_8_sports = countries_medals[countries_medals > 8]
countries_with_more_than_8_sports

noc
FIN    9
NOR    9
Name: sport, dtype: int64

In [ ]:
countries_gold_medals = df[df['medal'] == 'Gold'].groupby('noc').size()
countries_with_more_than_4_gold = countries_gold_medals[countries_gold_medals > 4]
countries_with_more_than_4_gold

noc
NOR    5
dtype: int64